### PR TITLE
Correct typo

### PR DESCRIPTION
**Pull request by 0323pin**
v0.2.5

2024-03-25-210528_996x484_scrot

### CODE REVIEW

**Comment by 0323pin** [comment]
@charklie I'll try 0.2.6 tomorrow, even though I'm not expecting the missing read-out for `de` to be fixed.

In a few days we will be cutting the next stable packages release and I think it would be nice to have `rsftch` in there. Is this possible?

**Comment by charklie** [comment]
> @charklie I'll try 0.2.6 tomorrow, even though I'm not expecting the missing read-out for `de` to be fixed.
> 
> 
> 
> In a few days we will be cutting the next stable packages release and I think it would be nice to have `rsftch` in there. Is this possible?

Probably, currently looking into how other rust-based fetches does it.

**Comment by charklie** [comment]
@0323pin just pushed 0.2.7, and i know for a fact it does solve the `de` issue. btw, is there anything special i need to do before it gets released into pkgsrc?

**Comment by 0323pin** [comment]
@charklie Cheers, I'll build 0.2.7 tomorrow and if, everything is working, I'll merge the package. We are currently on a commit freeze but, I've already asked the release responsible and got an "ok to commit".

The reason I want to do it now, is because we release every 3 months. It's not a problem if, like me, one is running the development branch but, for users running stable it wouldn't be available until the next release.

You don't need to do anything, I just need to move the package from one repository (wip) to another (main).
If, you like, I can do a PR here with install instructions if you would like that.

But, it's getting late here and I've switched off my system. Answering from mobile.

**Comment by charklie** [comment]
> @charklie Cheers, I'll build 0.2.7 tomorrow and if, everything is working, I'll merge the package. We are currently on a commit freeze but, I've already asked the release responsible and got an "ok to commit".
> 
> 
> 
> The reason I want to do it now, is because we release every 3 months. It's not a problem if, like me, one is running the development branch but, for users running stable it wouldn't be available until the next release.
> 
> 
> 
> You don't need to do anything, I just need to move the package from one repository (wip) to another (main).
> 
> If, you like, I can do a PR here with install instructions if you would like that.
> 
> 
> 
> But, it's getting late here and I've switched off my system. Answering from mobile.

Yeah no problem, let me know if it works tomorrow!

**Comment by 0323pin** [comment]
:partying_face: 

2024-03-27-053603_1366x768_scrot


I'll merge the package in a few hours. I was asked to expand on the description of the package, though. I.e. _"what does this program do, for those who don't know what a hardware fetch is"_.

I can of course, do this myself comparing it to neofetch and the likes. But, I want to give you a chance to have a say on it, as this is your project. Would you like to write a few more lines about it?

**Comment by 0323pin** [comment]
@charklie Would you agree with the following package description?

> Command-line tool that displays system information, i.e. operating system,
kernel version, uptime and more.
Rsftch works on GNU/Linux, (most) BSD distributions and Mac OS, although
windows support is planned.

**Comment by 0323pin** [comment]
Package merged into main now, http://mail-index.netbsd.org/pkgsrc-changes/2024/03/27/msg296068.html

I can change the description at a later stage.

**Pull request merged**
